/*Reiniciar contador auto_increment*/
ALTER TABLE `comunas` AUTO_INCREMENT = 0;


/*Poblar tabla regiones*/

insert into regiones VALUES(null, 'Región Metropolitana');
insert into regiones VALUES(null, 'Región de Tarapacá');
insert into regiones VALUES(null, 'Región de Antofagasta');
insert into regiones VALUES(null, 'Región de Atacama');
insert into regiones VALUES(null, 'Región de Coquimbo');
insert into regiones VALUES(null, 'Región de Valparaíso');
insert into regiones VALUES(null, 'Región del Libertador General Bernardo OHiggins');
insert into regiones VALUES(null, 'Región del Maule');
insert into regiones VALUES(null, 'Región del Bío Bío');
insert into regiones VALUES(null, 'Región de la Araucanía');
insert into regiones VALUES(null, 'Región de los Lagos');
insert into regiones VALUES(null, 'Región de los Ríos');
insert into regiones VALUES(null, 'Región de Arica y Parinacota');
insert into regiones VALUES(null, 'Región del Ñuble');

/*Poblar tabla regiones*/

insert into comunas VALUES(null, 1, 'Alhué');
insert into comunas VALUES(null, 1, 'Alto jahuel');
insert into comunas VALUES(null, 1, 'Batuco');
insert into comunas VALUES(null, 1, 'Bollenar');
insert into comunas VALUES(null, 1, 'Buin');
insert into comunas VALUES(null, 1, 'Calera de tango');
insert into comunas VALUES(null, 1, 'Caleu');
insert into comunas VALUES(null, 1, 'Cerrillos');
insert into comunas VALUES(null, 1, 'Cerro navia');
insert into comunas VALUES(null, 1, 'Champa');
insert into comunas VALUES(null, 1, 'Chicureo');
insert into comunas VALUES(null, 1, 'Colina');
insert into comunas VALUES(null, 1, 'Conchalí');
insert into comunas VALUES(null, 1, 'Curacaví');
insert into comunas VALUES(null, 1, 'El bosque');
insert into comunas VALUES(null, 1, 'El canelo');
insert into comunas VALUES(null, 1, 'El colorado');
insert into comunas VALUES(null, 1, 'El manzano');
insert into comunas VALUES(null, 1, 'El monte');
insert into comunas VALUES(null, 1, 'Esmeralda');
insert into comunas VALUES(null, 1, 'Estación central');
insert into comunas VALUES(null, 1, 'Farellones');
insert into comunas VALUES(null, 1, 'Huechuraba');
insert into comunas VALUES(null, 1, 'Huelquén');
insert into comunas VALUES(null, 1, 'Independencia');
insert into comunas VALUES(null, 1, 'Isla de maipo');
insert into comunas VALUES(null, 1, 'La cisterna');
insert into comunas VALUES(null, 1, 'La dehesa');
insert into comunas VALUES(null, 1, 'La florida');
insert into comunas VALUES(null, 1, 'La granja');
insert into comunas VALUES(null, 1, 'La obra');
insert into comunas VALUES(null, 1, 'La parva');
insert into comunas VALUES(null, 1, 'La pintana');
insert into comunas VALUES(null, 1, 'La reina');
insert into comunas VALUES(null, 1, 'Lampa');
insert into comunas VALUES(null, 1, 'Las canteras');
insert into comunas VALUES(null, 1, 'Las condes');
insert into comunas VALUES(null, 1, 'Las vertientes');
insert into comunas VALUES(null, 1, 'Las vizcachas');
insert into comunas VALUES(null, 1, 'Linderos');
insert into comunas VALUES(null, 1, 'Lo barnechea');
insert into comunas VALUES(null, 1, 'Lo curro');
insert into comunas VALUES(null, 1, 'Lo espejo');
insert into comunas VALUES(null, 1, 'Lo herrera');
insert into comunas VALUES(null, 1, 'Lo prado');
insert into comunas VALUES(null, 1, 'Lomas de lo aguirre');
insert into comunas VALUES(null, 1, 'Lonquén');
insert into comunas VALUES(null, 1, 'Macul');
insert into comunas VALUES(null, 1, 'Maipú');
insert into comunas VALUES(null, 1, 'Malloco');
insert into comunas VALUES(null, 1, 'María pinto');
insert into comunas VALUES(null, 1, 'Melipilla');
insert into comunas VALUES(null, 1, 'Melocotón');
insert into comunas VALUES(null, 1, 'Nos');
insert into comunas VALUES(null, 1, 'Noviciado');
insert into comunas VALUES(null, 1, 'Padre hurtado');
insert into comunas VALUES(null, 1, 'Paine');
insert into comunas VALUES(null, 1, 'Pedro aguirre cerda');
insert into comunas VALUES(null, 1, 'Peñaflor');
insert into comunas VALUES(null, 1, 'Peñalolén');
insert into comunas VALUES(null, 1, 'Pirque');
insert into comunas VALUES(null, 1, 'Pomaire');
insert into comunas VALUES(null, 1, 'Providencia');
insert into comunas VALUES(null, 1, 'Pudahuel');
insert into comunas VALUES(null, 1, 'Puente alto');
insert into comunas VALUES(null, 1, 'Quilicura');
insert into comunas VALUES(null, 1, 'Quinta normal');
insert into comunas VALUES(null, 1, 'Recoleta');
insert into comunas VALUES(null, 1, 'Renca');
insert into comunas VALUES(null, 1, 'Rungue');
insert into comunas VALUES(null, 1, 'San alfonso');
insert into comunas VALUES(null, 1, 'San bernardo');
insert into comunas VALUES(null, 1, 'San gabriel');
insert into comunas VALUES(null, 1, 'San joaquín');
insert into comunas VALUES(null, 1, 'San josé de maipo');
insert into comunas VALUES(null, 1, 'San manuel');
insert into comunas VALUES(null, 1, 'an miguel');
insert into comunas VALUES(null, 1, 'San pedro');
insert into comunas VALUES(null, 1, 'San ramón');
insert into comunas VALUES(null, 1, 'Santiago');
insert into comunas VALUES(null, 1, 'Talagante');
insert into comunas VALUES(null, 1, 'Til til');
insert into comunas VALUES(null, 1, 'Valle nevado');
insert into comunas VALUES(null, 1, 'Viluco');
insert into comunas VALUES(null, 1, 'Vitacura');
insert into comunas VALUES(null, 1, 'Ñuñoa');

/*Poblar comercios*/
insert into comercio VALUES(null, 'Falabella');
insert into comercio VALUES(null, 'Paris');
insert into comercio VALUES(null, 'Dijon');
insert into comercio VALUES(null, 'Lapolar');
insert into comercio VALUES(null, 'Tottus');
insert into comercio VALUES(null, 'Lider');
insert into comercio VALUES(null, 'Santa Isabel');
insert into comercio VALUES(null, 'Apple Store');
insert into comercio VALUES(null, 'Doite');
insert into comercio VALUES(null, 'Lippi');
insert into comercio VALUES(null, 'The North Face');
insert into comercio VALUES(null, 'Jumbo');
insert into comercio VALUES(null, 'Easy');
insert into comercio VALUES(null, 'Homecenter Sodimac');
insert into comercio VALUES(null, 'Construmart');
insert into comercio VALUES(null, 'Adidas');
insert into comercio VALUES(null, 'Nike');
insert into comercio VALUES(null, 'Under Armour');
insert into comercio VALUES(null, 'Fashions Park');